services:
  api:
    build: ./backend
    container_name : model_call
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: predict_front
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: my-postgres
    env_file:
      - .env
    ports:
      - "5000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbeaver -d logging_accident"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
